CREATE TABLE roles(
	role_id			VARCHAR(64)		PRIMARY KEY
);

CREATE TABLE account(
	id				VARCHAR(36)		PRIMARY KEY,
	role_id			VARCHAR(64)		REFERENCES roles(role_id),
	email			VARCHAR(128)	NOT NULL,
	password		VARCHAR(64)		NOT NULL,
	date_added		TIMESTAMP		WITH TIME ZONE NOT NULL DEFAULT NOW()
);
